#!/usr/bin/env node
/**
 * Build-time icon pre-bundler.
 *
 * Baca daftar icon yg dipakai di kategori default → ekstrak SVG body dari
 * @iconify/json → tulis ke `src/lib/iconify-bundled.ts`.
 *
 * File output di-import client-side via `addCollection()` saat app boot.
 * Hasilnya: icon kategori instan render tanpa network call.
 *
 * Jalankan via: `node scripts/build-iconify.mjs`
 * Atau di-hook ke `predev` & `prebuild` di package.json.
 */
import fs from "node:fs";
import path from "node:path";

const ICONS = [
  "solar:smartphone-2-bold-duotone",
  "solar:wi-fi-router-bold-duotone",
  "solar:phone-calling-bold-duotone",
  "solar:calendar-mark-bold-duotone",
  "solar:ticket-sale-bold-duotone",
  "solar:bolt-bold-duotone",
  "solar:wallet-money-bold-duotone",
  "solar:gameboy-bold-duotone",
  "solar:gift-bold-duotone",
  "solar:tv-bold-duotone",
  "solar:fire-bold-duotone",
  "solar:health-bold-duotone",
  "solar:shield-check-bold-duotone",
  "solar:water-bold-duotone",
  "solar:bus-bold-duotone",
  "solar:bag-2-bold-duotone",
  "solar:document-text-bold-duotone",
  "solar:widget-bold-duotone",
  "solar:wallet-bold-duotone",
  "solar:phone-bold-duotone",
  // Phosphor (suggestion form admin)
  "ph:phone-fill",
  "ph:wifi-high-fill",
  "ph:wallet-fill",
  "ph:game-controller-fill",
  "ph:lightning-fill",
  "ph:television-fill",
  "ph:gift-fill",
  "ph:ticket-fill",
];

// Group icons by prefix
const byPrefix = new Map();
for (const id of ICONS) {
  const [prefix, ...rest] = id.split(":");
  const name = rest.join(":");
  if (!prefix || !name) continue;
  const arr = byPrefix.get(prefix) ?? [];
  arr.push(name);
  byPrefix.set(prefix, arr);
}

const collections = [];
let totalIcons = 0;

for (const [prefix, names] of byPrefix.entries()) {
  const jsonPath = path.join(
    process.cwd(),
    "node_modules/@iconify/json/json",
    `${prefix}.json`,
  );
  if (!fs.existsSync(jsonPath)) {
    console.warn(`[iconify-bundle] skip "${prefix}" — file not found`);
    continue;
  }
  const raw = fs.readFileSync(jsonPath, "utf-8");
  const data = JSON.parse(raw);
  const sliced = {};
  for (const n of names) {
    if (data.icons?.[n]) {
      sliced[n] = data.icons[n];
    } else {
      console.warn(`[iconify-bundle] missing "${prefix}:${n}"`);
    }
  }
  const count = Object.keys(sliced).length;
  if (count === 0) continue;
  totalIcons += count;
  collections.push({
    prefix,
    icons: sliced,
    width: data.width ?? 24,
    height: data.height ?? 24,
  });
}

// Generate TS file
const ts = `// AUTO-GENERATED by scripts/build-iconify.mjs — DO NOT EDIT MANUALLY.
// Pre-bundled iconify icons supaya kategori topup render instan tanpa network.
//
// Untuk update list: edit scripts/build-iconify.mjs lalu jalankan ulang.

import type { IconifyJSON } from "@iconify/react";

export const BUNDLED_ICONS: IconifyJSON[] = ${JSON.stringify(
  collections,
  null,
  2,
)};
`;

const outPath = path.join(process.cwd(), "src/lib/iconify-bundled.ts");
fs.writeFileSync(outPath, ts);
console.log(
  `[iconify-bundle] wrote ${totalIcons} icons across ${collections.length} sets → ${outPath}`,
);
